Update dependencies and make structure maven conform
DevotedMC/ItemExchange pull request #2
Opened 2016-11-04 02:37 UTC by Maxopoly

2016-11-04 13:06 UTC, ProgrammerDan requested changes

2016-11-04 13:06 UTC, ProgrammerDan commented on pom.xml
> -          <include>*.csv</include>
Aren't these CSVs used by the built jar at runtime?

2016-11-04 13:38 UTC, Maxopoly commented on pom.xml
> -          <include>*.csv</include>
Arent they included automatically if moved into  src/main/resources?

2016-11-04 14:08 UTC, ProgrammerDan commented on pom.xml
> -          <include>*.csv</include>
Just tested here: https://build.devotedmc.com/job/Bastion-pullrequest/ws/target/classes/

answer is no :(

2016-11-04 14:15 UTC, Maxopoly commented on pom.xml
> -          <include>*.csv</include>
Ah okay, I thought that was the case. Will fix.

2016-11-05 03:56 UTC, Maxopoly commented on pom.xml
> -          <include>**/*.java</include>
What was the idea behind this?

2016-11-05 03:56 UTC, Maxopoly commented
Fixed

2016-11-05 17:07 UTC, ProgrammerDan commented on pom.xml
> -          <include>**/*.java</include>
I think someone was trying to include the sources in with the distribution jar, check the license, might be a requirement.

2016-11-05 18:03 UTC, Maxopoly commented on pom.xml
> -          <include>**/*.java</include>
That one seems to be standard BSD 3

2016-11-05 18:46 UTC, merged